"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$directory$character'
right_format = """$all"""
scan_timeout = 300
command_timeout = 1500

[docker_context]
disabled = true

[aws]
disabled = true

[nodejs]
symbol = '⬢ '

[package]
disabled = true
